import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./context/CartContext";
import { AuthProvider } from "./context/AuthContext";
import Navbar from "@/components/layout/navbar/Navbar";
import FooterContainer from "@/components/layout/footer/FooterContainer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "CherryBooks",
    description: "Generated by create next app",
};

export default function RootLayout({ children, auth, cart }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthProvider>
                    <CartProvider>
                        <div className="grid grid-rows-layout-principal w-full min-h-screen">
                            <Navbar/>
                            <main className="w-full justify-self-center flex justify-center flex-col items-center">
                                {children}
                                {auth}
                                {cart}
                            </main>
                            <FooterContainer/>
                        </div>
                    </CartProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
