import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./context/CartContext";
import { AuthProvider } from "./context/AuthContext";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "CherryBooks",
    description: "Generated by create next app",
};

export default function RootLayout({ children, auth, cart }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthProvider>
                    <CartProvider>
                        
                        
                        <div>{auth}</div>
                        <div>{cart}</div>

                        {children}
                    </CartProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
